from enum import Enum


class DotEnvEnum(Enum):
    MONGO_URI = "MONGO_URI"
    DATABASE_NAME = "DATABASE"
    WEATHER_FORECAST_API_KEY = "WEATHER_FORECAST_API_KEY"
    WEATHER_FORECAST_API_URL = "WEATHER_FORECAST_API_URL"
    DIRECT_GEOCODING_API_URL = "DIRECT_GEOCODING_API_URL"
